const SET_CURRENT = "SET_CURRENT_FILMS",
    GET_CURRENT = "GET_CURRENT_FILMS",
    SET_FAVORITES = "SET_FAVORITES_FILMS",
    DEL_FAVORITE = "DEL_FAVORITE",
    SET_DEFAULT_LIST = "SET_DEFAULT_LIST",
    LOGIN = "LOGIN",
    CLEAR_FAVORITE = "CLEAR_FAVORITE",
    LOGOUT = "LOGOUT";

export {
    SET_CURRENT,
    SET_FAVORITES,
    DEL_FAVORITE,
    SET_DEFAULT_LIST,
    GET_CURRENT,
    LOGIN,
    LOGOUT,
    CLEAR_FAVORITE
};
